version: '3.3'
services:

  postgres:
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immuunthai
    restart: always
    volumes:
      #- ./init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - /var/backups/immuunthai-db-prod:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
