version: '3.8'
services:
  wagtail:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres


  postgres:
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immuunthai
    restart: always
    volumes:
      #- ./init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - /var/backups/immuunthai-db-prod:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 55435:5432
