# Generated by Django 3.1.3 on 2020-12-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0003_auto_20201220_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
