# Generated by Django 3.1.3 on 2021-01-17 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_productpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='product_likers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
