# Generated by Django 3.1.3 on 2021-02-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productpage_product_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='product_likers',
        ),
    ]
