# Generated by Django 3.1.3 on 2021-02-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.base
import measurement.measures.energy
import measurement.measures.mass
import measurement.measures.time
import measurement.measures.volume
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=6, max_digits=5)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('scientific_name', models.CharField(blank=True, max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('energy_per_kg', django_measurement.models.MeasurementField(measurement=measurement.measures.energy.Energy)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IC', 'In Cart'), ('OR', 'Ordered'), ('AC', 'Accepted'), ('PR', 'In production'), ('CR', 'Created'), ('PA', 'Paid'), ('DE', 'Delivered')], default='IC', max_length=2)),
                ('delivery_date', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('workhour_multiplier', models.FloatField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('labour_multiplier', models.FloatField()),
                ('conserves_for', django_measurement.models.MeasurementField(measurement=measurement.measures.time.Time)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('to_taste', models.BooleanField()),
                ('amount_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('amount_volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume)),
                ('amount_units', django_measurement.models.MeasurementField(measurement=measurement.base.MeasureBase)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ingredient')),
                ('process_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.processmethod')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.recipe')),
                ('storage_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.storagemethod')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount_multiplier', models.FloatField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.recipe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCustomLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_trace_amount', models.BooleanField()),
                ('amount_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('amount_volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ingredient')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.nutrition')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_dangerous', models.BooleanField()),
                ('is_trace_amount', models.BooleanField()),
                ('amount_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('amount_volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.allergen')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ingredient')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
