# Generated by Django 3.1.3 on 2021-04-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.base
import measurement.measures.energy
import measurement.measures.mass
import measurement.measures.time
import measurement.measures.volume
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    #replaces = [('shop', '0001_squashed_0005_auto_20210308_0635'), ('shop', '0007_auto_20210312_0723'), ('shop', '0008_shoppreferences')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=6, max_digits=5)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('energy_per_kg', django_measurement.models.MeasurementField(measurement=measurement.measures.energy.Energy, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('labour_multiplier', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('base_servings', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('labour_multiplier', models.FloatField(default=1)),
                ('conserves_for', django_measurement.models.MeasurementField(measurement=measurement.measures.time.Time, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('is_trace_amount', models.BooleanField(default=False)),
                ('amount_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True)),
                ('amount_volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.allergen')),
                ('ingredient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='shop.ingredient')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_trace_amount', models.BooleanField(default=False)),
                ('amount_mass', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True)),
                ('amount_volume', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True)),
                ('ingredient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='shop.ingredient')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.nutrition')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IC', 'In Cart'), ('OR', 'Ordered'), ('AC', 'Accepted'), ('PR', 'In production'), ('CR', 'Created'), ('PA', 'Paid'), ('DE', 'Delivered')], default='IC', max_length=2)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCustomLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lines', to='shop.order')),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.recipe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('to_taste', models.BooleanField(blank=True, default=False, null=True)),
                ('amount_mass', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('amount_volume', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True)),
                ('amount_units', django_measurement.models.MeasurementField(blank=True, measurement=measurement.base.MeasureBase, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ingredient')),
                ('process_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.processmethod')),
                ('recipe', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shop.recipe')),
                ('storage_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.storagemethod')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),

        migrations.CreateModel(
            name='ShopPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_vat', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
