# Generated by Django 3.1.3 on 2021-03-07 16:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.base
import measurement.measures.energy
import measurement.measures.mass
import measurement.measures.time
import measurement.measures.volume
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('show_vat', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ordercustomline',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='base_servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vat_pct',
            field=models.DecimalField(decimal_places=1, default=21, max_digits=3),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='amount_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='amount_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='is_dangerous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='is_trace_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='amount_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='amount_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='is_trace_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='energy_per_kg',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.energy.Energy, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='scientific_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ordercustomline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lines', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='ordercustomline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderrecipe',
            name='amount_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderrecipe',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='processmethod',
            name='workhour_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_mass',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_units',
            field=django_measurement.models.MeasurementField(measurement=measurement.base.MeasureBase, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shop.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='to_taste',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='conserves_for',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.time.Time, null=True),
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='labour_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopuser'),
        ),
    ]
