# Generated by Django 3.1.3 on 2021-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_ingredient_add_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmethod',
            name='labour_multiplier',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='labour_multiplier',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
    ]
