# Generated by Django 3.1.3 on 2021-03-08 05:39

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210308_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='ingredient',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='shop.ingredient'),
        ),
    ]
