# Generated by Django 3.1.3 on 2021-04-24 07:57

from django.db import migrations, models
import django_measurement.models
import measurement.measures.energy
import measurement.measures.mass
import measurement.measures.time
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_process_storage_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('ml', 'ml'), (None, '')], default='kg', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='amount_mass',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientallergen',
            name='amount_volume',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='amount_mass',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='amount_volume',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='energy_per_kg',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.energy.Energy, null=True),
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='conserves_for',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.time.Time, null=True),
        ),
    ]
