# Generated by Django 3.1.3 on 2021-03-08 06:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210308_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.RenameField(
            model_name='processmethod',
            old_name='workhour_multiplier',
            new_name='labour_multiplier',
        ),
        migrations.AlterField(
            model_name='ordercustomline',
            name='order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lines', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderrecipe',
            name='order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shop.recipe'),
        ),
    ]
