# Generated by Django 3.1.3 on 2021-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_auto_20210508_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrecipe",
            name="sell_price",
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
    ]
