# Generated by Django 3.1.3 on 2021-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_orderrecipe_sell_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrecipe",
            name="sell_vat",
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
    ]
