# Generated by Django 3.1.3 on 2021-05-09 07:44
# Increase the max of total price for orderrcipes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_orderrecipe_sell_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercustomline",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name="orderrecipe",
            name="sell_price",
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderrecipe",
            name="sell_vat",
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9),
        ),
    ]
