# Generated by Django 3.1.10 on 2021-07-06 09:21

from django.db import migrations, models
import django_measurement.models
import measurement.base
import measurement.measures.mass
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_auto_20210509_0848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrecipe",
            name="amount_multiplier",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Aantal"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_mass",
            field=django_measurement.models.MeasurementField(
                blank=True,
                measurement=measurement.measures.mass.Mass,
                null=True,
                verbose_name="Massa",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_units",
            field=django_measurement.models.MeasurementField(
                blank=True, measurement=measurement.base.MeasureBase, null=True, verbose_name="Aantal"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount_volume",
            field=django_measurement.models.MeasurementField(
                blank=True,
                measurement=measurement.measures.volume.Volume,
                null=True,
                verbose_name="Volume",
            ),
        ),
    ]
