# Generated by Django 3.2.5 on 2021-07-10 17:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_auto_20210706_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrecipe",
            name="amount_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Aantal",
            ),
        ),
    ]
