# Generated by Django 3.2.5 on 2021-09-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20210904_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.allergen'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.nutrition'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='process_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.processmethod'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='storage_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.storagemethod'),
        ),
    ]
