# Generated by Django 3.2.5 on 2022-04-09 16:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_protect_orders_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ShopPreferences',
            name='allow_reminders',
            field=models.BooleanField(default=True, verbose_name='Sta herinnerings mails toe'),
        ),
        migrations.AddField(
            model_name='ShopPreferences',
            name='last_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Laatste keer dat er een herinnering werd gestuurd'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
